package at.kropf.curriculumvitae.augmented;

public class WikitudeSDKConstants {
	

	/**
	 * note that this key is only valid for this sample app, if you need one for your own application please visit www.wikitude.com (SDK Store)
	 */
	protected static final String WIKITUDE_SDK_KEY = "uSAax4x8XLj2N2GYsJ0zvh5zxV2yX/55sV+lFnxNgKWBFXV6QksUrBGPFIUfsHHVCiHksqXGx0sg8sCDgv3oNqrBTCROj7pF9xKcl76HPFuYT8bmT0uvx2OHP+JqgyObewHKAmOX4Q7hne1L/YukvUfu6IKDG9dgPkkcjuO2o+tTYWx0ZWRfX6NH2lN2C8S4fDKzPIMyqCi/yUMz+Mtz4FGnnxBgLyioRgPN+RA4K8yvQe7CTOHdAUaX30bZq7RGAJ3h1WimORs9uDSvBXyRKMy0PRaaGqB6+FjpAQNtoz9SaeEuBawuLDrr7lksWTO3L9lAyilmeCIAJlEh5nhv21Oj4pHfIsOW4dxzH/sza5+rtny5VgX6AgWyz0IJDGYN0QQ2UYeVXOiztqfEmXQpBYdV9OdqeFqDli/a9CbwWO8Su2O9DhDcMojJX9zJPL3nBHEZE3G+ysRA5IxxsW9RLyF9I6/qIRMkulSqRTDogVFV4TPrb05UtcNbSnfA1SBXny7OFdTOUceghxRUmFmAII/xSrl99LenWsbNg12ecG/jlkV0zDATdOhBIgsbbjsRs4LTLwwDtEg+UvjwOZ3xAG2zH2j7WNQEgHUNg68bbPybsz5XlfrQ/gOLqJqRzp1PTmLEwpyTxfhqOoHktD+foZJMeDyMB09VMvS1pp2mp2g=";
}
